import Head from 'next/head'
import React,{ useState, useEffect, useContext } from 'react'


import { ChatAppContext } from '../Context/ChatAppContext'

const Home = () => {

  return (
    <>
      <Head>
        <title> Blockchain Chat App </title>
        <meta name="description" content="Generated by create next app for Blockchain Chat App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Mohammed</div>
    </>
  )
}

export default Home;


